import {
  ItemRange,
  ItemTechTier,
  ItemWeapon
} from '../../character/item';
import { v4 } from 'uuid';
import { GeneralSkillType } from '../../character';
import { cellPowered, heavy, light, long, mercurium} from '../features';

export const knife: ItemWeapon = new ItemWeapon({
  name: 'Knife',
  id: v4(),
  baseSkill: GeneralSkillType.MeleeCombat,
  bonusModifier: 0,
  initModifier: 1,
  damage: 2,
  crit: 2,
  range: ItemRange.close,
  features: [light],
  techTier: ItemTechTier.primitive,
  cost: 50,
});
export const sword: ItemWeapon = new ItemWeapon({
  crit: 0,
  damage: 0,
  id: v4(),
  name: 'Sword',
  range: ItemRange.close,
  techTier: ItemTechTier.primitive,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const duraKnife: ItemWeapon = new ItemWeapon({
  name: 'Dura knife',
  id: v4(),
  bonusModifier: 0,
  initModifier: 1,
  damage: 2,
  crit: 1,
  range: ItemRange.close,
  features: [light, cellPowered],
  techTier: ItemTechTier.ordinary,
  cost: 500,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const duraSword: ItemWeapon = new ItemWeapon({
  name: 'Dura sword',
  id: v4(),
  bonusModifier: 1,
  initModifier: 0,
  damage: 2,
  crit: 1,
  range: ItemRange.close,
  features: [heavy, cellPowered],
  techTier: ItemTechTier.ordinary,
  cost: 1600,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const mercuriumKnife: ItemWeapon = new ItemWeapon({
  name: 'Mercurium knife',
  id: v4(),
  bonusModifier: 1,
  initModifier: 1,
  damage: 3,
  crit: 2,
  range: ItemRange.close,
  features: [light, mercurium, cellPowered],
  techTier: ItemTechTier.advanced,
  cost: 1500,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const mercuriumSword: ItemWeapon = new ItemWeapon({
  name: 'Mercurium sword',
  id: v4(),
  bonusModifier: 2,
  initModifier: 0,
  damage: 3,
  crit: 2,
  range: ItemRange.close,
  features: [heavy, mercurium, cellPowered],
  techTier: ItemTechTier.advanced,
  cost: 3000,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const axe: ItemWeapon = new ItemWeapon({
  name: 'Axe',
  id: v4(),
  bonusModifier: 0,
  initModifier: 0,
  damage: 3,
  crit: 2,
  range: ItemRange.close,
  features: [heavy],
  techTier: ItemTechTier.primitive,
  cost: 150,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const duraAxe: ItemWeapon = new ItemWeapon({
  name: 'Dura axe',
  id: v4(),
  bonusModifier: 0,
  initModifier: 0,
  damage: 3,
  crit: 1,
  range: ItemRange.close,
  features: [heavy, cellPowered],
  techTier: ItemTechTier.ordinary,
  cost: 2000,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const halberd: ItemWeapon = new ItemWeapon({
  name: 'Halberd',
  id: v4(),
  bonusModifier: 0,
  initModifier: 1,
  damage: 3,
  crit: 2,
  range: ItemRange.close,
  features: [heavy, long],
  techTier: ItemTechTier.primitive,
  cost: 300,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const duraHalberd: ItemWeapon = new ItemWeapon({
  name: 'Dura halberd',
  id: v4(),
  bonusModifier: 0,
  initModifier: 1,
  damage: 3,
  crit: 1,
  range: ItemRange.close,
  features: [heavy, long, cellPowered],
  techTier: ItemTechTier.ordinary,
  cost: 2500,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const baton: ItemWeapon = new ItemWeapon({
  name: 'Baton',
  id: v4(),
  bonusModifier: 2,
  initModifier: 0,
  damage: 1,
  crit: 3,
  range: ItemRange.close,
  techTier: ItemTechTier.primitive,
  cost: 100,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const batonExpandable: ItemWeapon = new ItemWeapon({
  name: 'Baton',
  id: v4(),
  bonusModifier: 2,
  initModifier: 0,
  damage: 1,
  crit: 3,
  range: ItemRange.close,
  features: [light],
  techTier: ItemTechTier.primitive,
  cost: 100,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const staff: ItemWeapon = new ItemWeapon({
  name: 'Staff',
  id: v4(),
  bonusModifier: 1,
  initModifier: 2,
  damage: 1,
  crit: 3,
  range: ItemRange.close,
  techTier: ItemTechTier.primitive,
  cost: 50,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const mace: ItemWeapon = new ItemWeapon({
  name: 'Mace',
  id: v4(),
  bonusModifier: 0,
  initModifier: 0,
  damage: 3,
  crit: 3,
  range: ItemRange.close,
  // itemFeatures: [ItemFeatures.heavy],
  techTier: ItemTechTier.primitive,
  cost: 100,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const powerSledge: ItemWeapon = new ItemWeapon({
  name: 'Power sledge',
  id: v4(),
  bonusModifier: 0,
  initModifier: 0,
  damage: 4,
  crit: 3,
  range: ItemRange.close,
  // itemFeatures: [ItemFeatures.heavy, ItemFeatures.cellPowered],
  techTier: ItemTechTier.ordinary,
  cost: 1000,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const powerGlove: ItemWeapon = new ItemWeapon({
  name: 'Power glove',
  id: v4(),
  bonusModifier: 1,
  initModifier: 1,
  damage: 2,
  crit: 3,
  range: ItemRange.close,
  // itemFeatures: [ItemFeatures.light, ItemFeatures.small, ItemFeatures.cellPowered],
  techTier: ItemTechTier.ordinary,
  cost: 1500,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const shockStick: ItemWeapon = new ItemWeapon({
  name: 'Shock stick',
  id: v4(),
  bonusModifier: 2,
  initModifier: 0,
  damage: 1,
  crit: 0,
  range: ItemRange.close,
  // itemFeatures: [ItemFeatures.stun, ItemFeatures.cellPowered],
  techTier: ItemTechTier.ordinary,
  cost: 500,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const shockWhip: ItemWeapon = new ItemWeapon({
  name: 'Shock whip',
  id: v4(),
  bonusModifier: 0,
  initModifier: 2,
  damage: 1,
  crit: 0,
  range: ItemRange.close,
  // itemFeatures: [ItemFeatures.light, ItemFeatures.small, ItemFeatures.flexible, ItemFeatures.stun, ItemFeatures.cellPowered],
  techTier: ItemTechTier.ordinary,
  cost: 800,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const energyStaff: ItemWeapon = new ItemWeapon({
  name: 'Energy staff',
  id: v4(),
  bonusModifier: 2,
  initModifier: 2,
  damage: 2,
  crit: 3,
  range: ItemRange.close,
  // itemFeatures: [ItemFeatures.stun, ItemFeatures.heavy, ItemFeatures.cellPowered],
  techTier: ItemTechTier.advanced,
  cost: 1000,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const energyStick: ItemWeapon = new ItemWeapon({
  name: 'Energy stick',
  id: v4(),
  bonusModifier: 2,
  initModifier: 0,
  damage: 2,
  crit: 3,
  range: ItemRange.close,
  // itemFeatures: [ItemFeatures.stun, ItemFeatures.cellPowered],
  techTier: ItemTechTier.advanced,
  cost: 1200,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const energyWhip: ItemWeapon = new ItemWeapon({
  name: 'Energy whip',
  id: v4(),
  bonusModifier: 0,
  initModifier: 2,
  damage: 2,
  crit: 3,
  range: ItemRange.close,
  // itemFeatures: [ItemFeatures.light, ItemFeatures.small, ItemFeatures.flexible, ItemFeatures.stun, ItemFeatures.cellPowered],
  techTier: ItemTechTier.advanced,
  cost: 1800,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const handFan: ItemWeapon = new ItemWeapon({
  name: 'Hand fan',
  id: v4(),
  bonusModifier: 1,
  initModifier: 2,
  damage: 2,
  crit: 1,
  range: ItemRange.close,
  // itemFeatures: [ItemFeatures.light, ItemFeatures.small, ItemFeatures.cellPowered],
  techTier: ItemTechTier.advanced,
  cost: 2500,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const unarmed: ItemWeapon = new ItemWeapon({
  name: 'Unarmed',
  id: v4(),
  bonusModifier: 0,
  initModifier: 2,
  damage: 1,
  crit: 3,
  range: ItemRange.close,
  techTier: ItemTechTier.primitive,
  cost: 0,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const brassKnuckles: ItemWeapon = new ItemWeapon({
  name: 'Brass knuckles',
  id: v4(),
  bonusModifier: 0,
  initModifier: 2,
  damage: 2,
  crit: 3,
  range: ItemRange.close,
  // itemFeatures: [ItemFeatures.light, ItemFeatures.small],
  techTier: ItemTechTier.primitive,
  cost: 50,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const claws: ItemWeapon = new ItemWeapon({
  name: 'Claws',
  id: v4(),
  bonusModifier: 0,
  initModifier: 2,
  damage: 1,
  crit: 2,
  range: ItemRange.close,
  techTier: ItemTechTier.primitive,
  cost: 0,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const duraClaws: ItemWeapon = new ItemWeapon({
  name: 'Dura claws',
  id: v4(),
  bonusModifier: 0,
  initModifier: 2,
  damage: 1,
  crit: 1,
  range: ItemRange.close,
  features: [light],
  // itemFeatures: [ItemFeatures.light, ItemFeatures.small],
  techTier: ItemTechTier.ordinary,
  cost: 600,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const spear: ItemWeapon = new ItemWeapon({
  name: 'Spear',
  id: v4(),
  bonusModifier: 1,
  initModifier: 2,
  damage: 2,
  crit: 2,
  range: ItemRange.close,
  // itemFeatures: [ItemFeatures.long],
  techTier: ItemTechTier.primitive,
  cost: 200,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const whip: ItemWeapon = new ItemWeapon({
  name: 'Whip',
  id: v4(),
  bonusModifier: 0,
  initModifier: 2,
  damage: 1,
  crit: 4,
  range: ItemRange.close,
  // itemFeatures: [ItemFeatures.flexible],
  techTier: ItemTechTier.primitive,
  cost: 50,
  baseSkill: GeneralSkillType.MeleeCombat,
});

export const allMeleeWeapons = {
  knife,
  sword,
  duraKnife,
  duraSword,
  mercuriumKnife,
  mercuriumSword,
  axe,
  duraAxe,
  halberd,
  duraHalberd,
  baton,
  staff,
  mace,
  powerSledge,
  powerGlove,
  shockStick,
  shockWhip,
  energyStaff,
  energyStick,
  energyWhip,
  handFan,
  unarmed,
  brassKnuckles,
  claws,
  duraClaws,
  spear,
  whip,
};
