import {
  ItemMeleeWeaponSubCategory,
  ItemRange,
  ItemTechTier,
  ItemWeapon,
} from '../../character/item';
import { v4 } from 'uuid';
import { GeneralSkillType } from '../../character';
import {
  cellPowered, flexibleWeapon,
  heavyWeapon,
  lightWeapon,
  longWeapon,
  mercurium, stun
} from '../features';

export const knife: ItemWeapon = new ItemWeapon({
  name: 'Knife',
  itemSubCategory: ItemMeleeWeaponSubCategory.knivesAndSwords,
  id: v4(),
  baseSkill: GeneralSkillType.MeleeCombat,
  bonusModifier: 0,
  initModifier: 1,
  damage: 2,
  crit: 2,
  range: ItemRange.close,
  features: [lightWeapon],
  techTier: ItemTechTier.primitive,
  cost: 50,
});
export const sword: ItemWeapon = new ItemWeapon({
  itemSubCategory: ItemMeleeWeaponSubCategory.knivesAndSwords,
  bonusModifier: 1,
  initModifier: 0,
  damage: 2,
  crit: 0,
  id: v4(),
  name: 'Sword',
  range: ItemRange.close,
  techTier: ItemTechTier.primitive,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const duraKnife: ItemWeapon = new ItemWeapon({
  name: 'Dura knife',
  itemSubCategory: ItemMeleeWeaponSubCategory.knivesAndSwords,
  id: v4(),
  bonusModifier: 0,
  initModifier: 1,
  damage: 2,
  crit: 1,
  range: ItemRange.close,
  features: [lightWeapon, cellPowered],
  techTier: ItemTechTier.ordinary,
  cost: 500,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const duraSword: ItemWeapon = new ItemWeapon({
  name: 'Dura sword',
  itemSubCategory: ItemMeleeWeaponSubCategory.knivesAndSwords,
  id: v4(),
  bonusModifier: 1,
  initModifier: 0,
  damage: 2,
  crit: 1,
  range: ItemRange.close,
  features: [heavyWeapon, cellPowered],
  techTier: ItemTechTier.ordinary,
  cost: 1600,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const mercuriumKnife: ItemWeapon = new ItemWeapon({
  name: 'Mercurium knife',
  itemSubCategory: ItemMeleeWeaponSubCategory.knivesAndSwords,
  id: v4(),
  bonusModifier: 1,
  initModifier: 1,
  damage: 3,
  crit: 2,
  range: ItemRange.close,
  features: [lightWeapon, mercurium, cellPowered],
  techTier: ItemTechTier.advanced,
  cost: 1500,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const mercuriumSword: ItemWeapon = new ItemWeapon({
  name: 'Mercurium sword',
  itemSubCategory: ItemMeleeWeaponSubCategory.knivesAndSwords,
  id: v4(),
  bonusModifier: 2,
  initModifier: 0,
  damage: 3,
  crit: 2,
  range: ItemRange.close,
  features: [heavyWeapon, mercurium, cellPowered],
  techTier: ItemTechTier.advanced,
  cost: 3000,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const axe: ItemWeapon = new ItemWeapon({
  name: 'Axe',
  itemSubCategory: ItemMeleeWeaponSubCategory.axes,
  id: v4(),
  bonusModifier: 0,
  initModifier: 0,
  damage: 3,
  crit: 2,
  range: ItemRange.close,
  features: [heavyWeapon],
  techTier: ItemTechTier.primitive,
  cost: 150,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const duraAxe: ItemWeapon = new ItemWeapon({
  name: 'Dura axe',
  itemSubCategory: ItemMeleeWeaponSubCategory.axes,
  id: v4(),
  bonusModifier: 0,
  initModifier: 0,
  damage: 3,
  crit: 1,
  range: ItemRange.close,
  features: [heavyWeapon, cellPowered],
  techTier: ItemTechTier.ordinary,
  cost: 2000,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const halberd: ItemWeapon = new ItemWeapon({
  name: 'Halberd',
  itemSubCategory: ItemMeleeWeaponSubCategory.axes,
  id: v4(),
  bonusModifier: 0,
  initModifier: 1,
  damage: 3,
  crit: 2,
  range: ItemRange.close,
  features: [heavyWeapon, longWeapon],
  techTier: ItemTechTier.primitive,
  cost: 300,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const duraHalberd: ItemWeapon = new ItemWeapon({
  name: 'Dura halberd',
  itemSubCategory: ItemMeleeWeaponSubCategory.axes,
  id: v4(),
  bonusModifier: 0,
  initModifier: 1,
  damage: 3,
  crit: 1,
  range: ItemRange.close,
  features: [heavyWeapon, longWeapon, cellPowered],
  techTier: ItemTechTier.ordinary,
  cost: 2500,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const baton: ItemWeapon = new ItemWeapon({
  name: 'Baton',
  itemSubCategory: ItemMeleeWeaponSubCategory.blunt,
  id: v4(),
  bonusModifier: 2,
  initModifier: 0,
  damage: 1,
  crit: 3,
  range: ItemRange.close,
  techTier: ItemTechTier.primitive,
  cost: 100,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const batonExpandable: ItemWeapon = new ItemWeapon({
  name: 'Baton expandable',
  itemSubCategory: ItemMeleeWeaponSubCategory.blunt,
  id: v4(),
  bonusModifier: 2,
  initModifier: 0,
  damage: 1,
  crit: 3,
  range: ItemRange.close,
  features: [lightWeapon],
  techTier: ItemTechTier.primitive,
  cost: 200,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const staff: ItemWeapon = new ItemWeapon({
  name: 'Staff',
  itemSubCategory: ItemMeleeWeaponSubCategory.blunt,
  id: v4(),
  bonusModifier: 1,
  initModifier: 2,
  damage: 1,
  crit: 3,
  range: ItemRange.close,
  techTier: ItemTechTier.primitive,
  cost: 50,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const mace: ItemWeapon = new ItemWeapon({
  name: 'Mace',
  itemSubCategory: ItemMeleeWeaponSubCategory.blunt,
  id: v4(),
  bonusModifier: 0,
  initModifier: 0,
  damage: 3,
  crit: 3,
  range: ItemRange.close,
  features: [heavyWeapon],
  techTier: ItemTechTier.primitive,
  cost: 100,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const powerSledge: ItemWeapon = new ItemWeapon({
  name: 'Power sledge',
  itemSubCategory: ItemMeleeWeaponSubCategory.blunt,
  id: v4(),
  bonusModifier: 0,
  initModifier: 0,
  damage: 4,
  crit: 3,
  range: ItemRange.close,
  features: [heavyWeapon, cellPowered],
  techTier: ItemTechTier.ordinary,
  cost: 1000,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const powerGlove: ItemWeapon = new ItemWeapon({
  name: 'Power glove',
  itemSubCategory: ItemMeleeWeaponSubCategory.blunt,
  id: v4(),
  bonusModifier: 1,
  initModifier: 1,
  damage: 2,
  crit: 3,
  range: ItemRange.close,
  features: [lightWeapon, { name: "small" }, cellPowered],
  techTier: ItemTechTier.ordinary,
  cost: 1500,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const shockStick: ItemWeapon = new ItemWeapon({
  name: 'Shock stick',
  itemSubCategory: ItemMeleeWeaponSubCategory.stunAndEnergy,
  id: v4(),
  bonusModifier: 2,
  initModifier: 0,
  damage: 1,
  crit: 0,
  range: ItemRange.close,
  features: [stun, cellPowered],
  techTier: ItemTechTier.ordinary,
  cost: 500,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const shockWhip: ItemWeapon = new ItemWeapon({
  name: 'Shock whip',
  itemSubCategory: ItemMeleeWeaponSubCategory.stunAndEnergy,
  id: v4(),
  bonusModifier: 0,
  initModifier: 2,
  damage: 1,
  crit: 0,
  range: ItemRange.close,
  features: [lightWeapon, { name: "small" }, flexibleWeapon, stun, cellPowered],
  techTier: ItemTechTier.ordinary,
  cost: 800,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const energyStaff: ItemWeapon = new ItemWeapon({
  name: 'Energy staff',
  itemSubCategory: ItemMeleeWeaponSubCategory.stunAndEnergy,
  id: v4(),
  bonusModifier: 2,
  initModifier: 2,
  damage: 2,
  crit: 3,
  range: ItemRange.close,
  features: [stun, heavyWeapon, cellPowered],
  techTier: ItemTechTier.advanced,
  cost: 1000,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const energyStick: ItemWeapon = new ItemWeapon({
  name: 'Energy stick',
  itemSubCategory: ItemMeleeWeaponSubCategory.stunAndEnergy,
  id: v4(),
  bonusModifier: 2,
  initModifier: 0,
  damage: 2,
  crit: 3,
  range: ItemRange.close,
  features: [stun, cellPowered],
  techTier: ItemTechTier.advanced,
  cost: 1200,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const energyWhip: ItemWeapon = new ItemWeapon({
  name: 'Energy whip',
  itemSubCategory: ItemMeleeWeaponSubCategory.stunAndEnergy,
  id: v4(),
  bonusModifier: 0,
  initModifier: 2,
  damage: 2,
  crit: 3,
  range: ItemRange.close,
  features: [lightWeapon, { name: "small" }, flexibleWeapon, stun, cellPowered],
  techTier: ItemTechTier.advanced,
  cost: 1800,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const handFan: ItemWeapon = new ItemWeapon({
  name: 'Hand fan',
  itemSubCategory: ItemMeleeWeaponSubCategory.stunAndEnergy,
  id: v4(),
  bonusModifier: 1,
  initModifier: 2,
  damage: 2,
  crit: 1,
  range: ItemRange.close,
  features: [lightWeapon, { name: "small" }, cellPowered],
  techTier: ItemTechTier.advanced,
  cost: 2500,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const unarmed: ItemWeapon = new ItemWeapon({
  name: 'Unarmed',
  itemSubCategory: ItemMeleeWeaponSubCategory.other,
  id: v4(),
  bonusModifier: 0,
  initModifier: 2,
  damage: 1,
  crit: 3,
  range: ItemRange.close,
  techTier: ItemTechTier.primitive,
  cost: 0,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const brassKnuckles: ItemWeapon = new ItemWeapon({
  name: 'Brass knuckles',
  itemSubCategory: ItemMeleeWeaponSubCategory.other,
  id: v4(),
  bonusModifier: 0,
  initModifier: 2,
  damage: 2,
  crit: 3,
  range: ItemRange.close,
  features: [lightWeapon, { name: "small" }],
  techTier: ItemTechTier.primitive,
  cost: 50,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const claws: ItemWeapon = new ItemWeapon({
  name: 'Claws',
  itemSubCategory: ItemMeleeWeaponSubCategory.other,
  id: v4(),
  bonusModifier: 0,
  initModifier: 2,
  damage: 1,
  crit: 2,
  range: ItemRange.close,
  techTier: ItemTechTier.primitive,
  cost: 0,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const duraClaws: ItemWeapon = new ItemWeapon({
  name: 'Dura claws',
  itemSubCategory: ItemMeleeWeaponSubCategory.other,
  id: v4(),
  bonusModifier: 0,
  initModifier: 2,
  damage: 1,
  crit: 1,
  range: ItemRange.close,
  features: [lightWeapon, { name: "small" }],
  techTier: ItemTechTier.ordinary,
  cost: 600,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const spear: ItemWeapon = new ItemWeapon({
  name: 'Spear',
  itemSubCategory: ItemMeleeWeaponSubCategory.other,
  id: v4(),
  bonusModifier: 1,
  initModifier: 2,
  damage: 2,
  crit: 2,
  range: ItemRange.close,
  features: [longWeapon],
  techTier: ItemTechTier.primitive,
  cost: 200,
  baseSkill: GeneralSkillType.MeleeCombat,
});
export const whip: ItemWeapon = new ItemWeapon({
  name: 'Whip',
  itemSubCategory: ItemMeleeWeaponSubCategory.other,
  id: v4(),
  bonusModifier: 0,
  initModifier: 2,
  damage: 1,
  crit: 4,
  range: ItemRange.close,
  features: [flexibleWeapon],
  techTier: ItemTechTier.primitive,
  cost: 50,
  baseSkill: GeneralSkillType.MeleeCombat,
});

export const meleeWeaponsList = {
  knife,
  sword,
  duraKnife,
  duraSword,
  mercuriumKnife,
  mercuriumSword,

  axe,
  duraAxe,
  halberd,
  duraHalberd,

  baton,
  batonExpandable,
  staff,
  mace,
  powerSledge,
  powerGlove,

  shockStick,
  shockWhip,
  energyStaff,
  energyStick,
  energyWhip,
  handFan,

  unarmed,
  brassKnuckles,
  claws,
  duraClaws,
  spear,
  whip,
};
