export enum CharacterGroupTalent {
  ANoseForBirr = 'ANoseForBirr',
  EveryThingIsForSale = 'EveryThingIsForSale',
  QuickestRoute = 'QuickestRoute',
  Assault = 'Assault',
  Charge = 'Charge',
  SituationalAwareness = 'SituationalAwareness',
  AFriendInEveryPort = 'AFriendInEveryPort',
  AssasinsGuild = 'AssasinsGuild',
  DancersOfAhlam = 'DancersOfAhlam',
  SeasonedTravelers = 'SeasonedTravelers',
  Survivors = 'Survivors',
  TruthSeekers = 'TruthSeekers',
  LastLaugh = 'LastLaugh',
  MercyOfTheIcons = 'MercyOfTheIcons',
  OneLastBirr = 'OneLastBirr',
}
